// 국내 대기업 30종목 메타데이터 (학생 친숙 종목)
// 기술가정 연계: products 필드로 "이 회사가 만드는 물건" 노출
window.SSAMJI_STOCKS = [
  { ticker:'005930', name:'삼성전자', sector:'반도체·전자', logo:'📱',
    products:['갤럭시 스마트폰','메모리 반도체','TV·냉장고'],
    description:'세계 최대 메모리 반도체 제조사이자 갤럭시 스마트폰을 만드는 회사. 대한민국 시가총액 1위.',
    initialPrice:81000, drift:0.06, vol:0.28, category:'tech' },
  { ticker:'000660', name:'SK하이닉스', sector:'반도체', logo:'💾',
    products:['D램','낸드플래시','HBM(AI 반도체 메모리)'],
    description:'세계 2위 메모리 반도체 회사. AI 시대 필수품인 HBM을 삼성보다 먼저 성공.',
    initialPrice:118000, drift:0.10, vol:0.35, category:'tech' },
  { ticker:'373220', name:'LG에너지솔루션', sector:'2차전지', logo:'🔋',
    products:['전기차 배터리','ESS 배터리','노트북 배터리'],
    description:'테슬라·현대차·GM에 배터리를 공급하는 세계 2위 전기차 배터리 회사.',
    initialPrice:500000, drift:0.02, vol:0.35, category:'battery' },
  { ticker:'207940', name:'삼성바이오로직스', sector:'제약·바이오', logo:'💊',
    products:['바이오의약품 위탁생산(CMO)','신약 개발'],
    description:'세계 최대 바이오의약품 위탁생산 회사. 화이자·모더나 등의 백신·의약품을 대신 만들어 줌.',
    initialPrice:830000, drift:0.08, vol:0.30, category:'bio' },
  { ticker:'005380', name:'현대차', sector:'자동차', logo:'🚗',
    products:['그랜저','아이오닉','제네시스','수소전기차'],
    description:'세계 3위 자동차 그룹. 전기차 아이오닉과 프리미엄 브랜드 제네시스로 유명.',
    initialPrice:210000, drift:0.05, vol:0.25, category:'auto' },
  { ticker:'000270', name:'기아', sector:'자동차', logo:'🚙',
    products:['쏘렌토','스포티지','K5','EV6'],
    description:'현대차 그룹의 두 번째 완성차 회사. SUV와 전기차 EV6로 해외에서도 인기.',
    initialPrice:60000, drift:0.09, vol:0.28, category:'auto' },
  { ticker:'035420', name:'NAVER', sector:'IT·인터넷', logo:'🟢',
    products:['네이버 검색','네이버 웹툰','네이버페이','라인'],
    description:'한국 최대 포털·검색 회사. 웹툰·페이·클라우드까지 사업 확장.',
    initialPrice:293000, drift:-0.02, vol:0.32, category:'tech' },
  { ticker:'035720', name:'카카오', sector:'IT·인터넷', logo:'💛',
    products:['카카오톡','카카오페이','카카오뱅크','카카오T'],
    description:'카카오톡을 중심으로 은행·택시·페이까지 확장한 대표 IT 회사.',
    initialPrice:78000, drift:-0.08, vol:0.38, category:'tech' },
  { ticker:'066570', name:'LG전자', sector:'전자·가전', logo:'📺',
    products:['OLED TV','냉장고·세탁기','시그니처 가전'],
    description:'세계 1위 OLED TV 제조사. 프리미엄 가전 브랜드 시그니처로 유명.',
    initialPrice:150000, drift:0.02, vol:0.24, category:'tech' },
  { ticker:'006400', name:'삼성SDI', sector:'2차전지', logo:'🔌',
    products:['전기차 배터리','ESS','전자재료'],
    description:'BMW·아우디 등 유럽 프리미엄 전기차에 배터리를 공급하는 회사.',
    initialPrice:640000, drift:0.03, vol:0.32, category:'battery' },
  { ticker:'051910', name:'LG화학', sector:'화학·소재', logo:'🧪',
    products:['석유화학','배터리 소재','LG생명과학'],
    description:'국내 최대 화학 회사. 자회사 LG에너지솔루션 상장 후 화학·소재에 집중.',
    initialPrice:820000, drift:-0.02, vol:0.28, category:'chem' },
  { ticker:'005490', name:'POSCO홀딩스', sector:'철강·소재', logo:'⚙️',
    products:['철강(자동차·조선용)','리튬','2차전지 소재'],
    description:'세계 6위 철강회사. 최근 리튬·양극재 등 배터리 소재 사업 확장 중.',
    initialPrice:290000, drift:0.04, vol:0.30, category:'steel' },
  { ticker:'105560', name:'KB금융', sector:'금융', logo:'🏦',
    products:['국민은행','KB증권','KB카드','KB손해보험'],
    description:'국내 최대 종합금융그룹. 국민은행이 주력.',
    initialPrice:45000, drift:0.07, vol:0.22, category:'finance' },
  { ticker:'055550', name:'신한지주', sector:'금융', logo:'🏛️',
    products:['신한은행','신한카드','신한투자증권'],
    description:'국내 2위 금융지주. 배당을 많이 주는 대표적인 배당주.',
    initialPrice:38000, drift:0.06, vol:0.20, category:'finance' },
  { ticker:'068270', name:'셀트리온', sector:'제약·바이오', logo:'💉',
    products:['바이오시밀러(램시마 등)','자체 신약 개발'],
    description:'유럽·미국에 바이오시밀러(복제 바이오의약품)를 파는 대표 바이오 회사.',
    initialPrice:230000, drift:-0.03, vol:0.34, category:'bio' },
  { ticker:'259960', name:'크래프톤', sector:'게임', logo:'🎮',
    products:['배틀그라운드','펍지 모바일','인디게임'],
    description:'배틀그라운드로 세계적 인기를 얻은 게임 회사. 인도 시장에서 특히 강함.',
    initialPrice:490000, drift:-0.04, vol:0.40, category:'game' },
  { ticker:'352820', name:'하이브', sector:'엔터테인먼트', logo:'🎤',
    products:['BTS','뉴진스','세븐틴','위버스 팬 플랫폼'],
    description:'BTS 소속사에서 시작해 뉴진스·세븐틴까지 거느린 세계 최대 K-POP 회사.',
    initialPrice:290000, drift:0.02, vol:0.38, category:'ent' },
  { ticker:'035900', name:'JYP Ent.', sector:'엔터테인먼트', logo:'🎵',
    products:['트와이스','스트레이키즈','ITZY','엔믹스'],
    description:'박진영이 세운 3대 엔터 중 하나. 일본·미국에서도 성공적으로 확장.',
    initialPrice:47000, drift:0.03, vol:0.36, category:'ent' },
  { ticker:'036570', name:'엔씨소프트', sector:'게임', logo:'⚔️',
    products:['리니지M','리니지W','TL(쓰론앤리버티)'],
    description:'리니지로 유명한 국내 대표 MMORPG 회사. 최근 신작 부진으로 어려움.',
    initialPrice:930000, drift:-0.15, vol:0.42, category:'game' },
  { ticker:'293490', name:'카카오게임즈', sector:'게임', logo:'🎯',
    products:['오딘','우마무스메','아키에이지 워'],
    description:'카카오 계열 게임 퍼블리셔. 오딘으로 큰 성공을 거둔 뒤 후속작 준비 중.',
    initialPrice:55000, drift:-0.10, vol:0.42, category:'game' },
  { ticker:'097950', name:'CJ제일제당', sector:'식품', logo:'🍚',
    products:['비비고 만두·김치','햇반','다시다','슈완스(미국)'],
    description:'세계 만두 시장 1위. 비비고 브랜드로 K-푸드 세계화를 이끔.',
    initialPrice:400000, drift:0.03, vol:0.22, category:'food' },
  { ticker:'271560', name:'오리온', sector:'식품', logo:'🍫',
    products:['초코파이','포카칩','오!감자','중국·베트남 판매'],
    description:'초코파이의 그 회사. 중국·베트남·러시아에서도 매출이 큰 글로벌 제과회사.',
    initialPrice:140000, drift:0.02, vol:0.22, category:'food' },
  { ticker:'004370', name:'농심', sector:'식품', logo:'🍜',
    products:['신라면','짜파게티','새우깡','너구리'],
    description:'신라면·짜파게티의 그 회사. 영화 "기생충" 이후 짜파구리로 미국 매출 급증.',
    initialPrice:260000, drift:0.06, vol:0.24, category:'food' },
  { ticker:'005300', name:'롯데칠성', sector:'식품·음료', logo:'🥤',
    products:['칠성사이다','펩시','처음처럼','새로'],
    description:'국내 최대 음료·주류 회사. 사이다·소주·맥주까지 다 취급.',
    initialPrice:150000, drift:0.02, vol:0.20, category:'food' },
  { ticker:'090430', name:'아모레퍼시픽', sector:'화장품', logo:'💄',
    products:['설화수','라네즈','이니스프리','헤라'],
    description:'K-뷰티 대표 화장품 회사. 설화수·라네즈로 중국·미국에서 인기.',
    initialPrice:245000, drift:-0.06, vol:0.30, category:'cosmetic' },
  { ticker:'051900', name:'LG생활건강', sector:'생활용품·화장품', logo:'🧴',
    products:['후(궁중화장품)','엘라스틴','페리오','코카콜라 국내판'],
    description:'후·숨 등 럭셔리 화장품과 생활용품·음료를 함께 하는 종합 소비재 회사.',
    initialPrice:1500000, drift:-0.10, vol:0.28, category:'cosmetic' },
  { ticker:'139480', name:'이마트', sector:'유통', logo:'🛒',
    products:['이마트 매장','트레이더스','스타벅스코리아','SSG닷컴'],
    description:'국내 최대 대형마트. 스타벅스 코리아·SSG닷컴도 자회사.',
    initialPrice:170000, drift:-0.05, vol:0.24, category:'retail' },
  { ticker:'004170', name:'신세계', sector:'유통', logo:'🏬',
    products:['신세계백화점','면세점','조선호텔'],
    description:'국내 대표 백화점·면세점 회사. 이마트와 같은 신세계 그룹.',
    initialPrice:260000, drift:0.02, vol:0.26, category:'retail' },
  { ticker:'003490', name:'대한항공', sector:'항공·운송', logo:'✈️',
    products:['국제선 여객·화물','아시아나 합병 진행'],
    description:'국내 1위 항공사. 코로나 이후 화물로 큰돈 벌었고 아시아나와 합병 중.',
    initialPrice:26000, drift:0.05, vol:0.26, category:'transport' },
  { ticker:'017670', name:'SK텔레콤', sector:'통신', logo:'📡',
    products:['5G 이동통신','T우주 구독','SK브로드밴드'],
    description:'국내 1위 이동통신사. 배당을 많이 주는 대표 배당주 중 하나.',
    initialPrice:47000, drift:0.03, vol:0.16, category:'telecom' }
];

// 카테고리별 라벨 (필터 칩용)
window.SSAMJI_CATEGORIES = {
  tech:'💻 IT·전자', battery:'🔋 배터리', bio:'💊 바이오', auto:'🚗 자동차',
  chem:'🧪 화학·소재', steel:'⚙️ 철강', finance:'🏦 금융', game:'🎮 게임',
  ent:'🎤 엔터', food:'🍚 식품', cosmetic:'💄 화장품', retail:'🛒 유통',
  transport:'✈️ 항공·운송', telecom:'📡 통신'
};

// 경제 개념 미니 카드 (학습 탭)
window.SSAMJI_CONCEPTS = [
  { id:'stock', title:'주식이 뭐야?', icon:'📈',
    body:'회사가 사업 자금이 필요할 때 「이 회사의 조각」을 파는 게 주식. 주식을 사면 그 회사의 아주 작은 주인이 됨. 회사가 잘 되면 주식 값이 오르고 배당(이익 나눔)도 받을 수 있어.' },
  { id:'price', title:'왜 주가는 매일 오르내려?', icon:'📊',
    body:'주가는 그 순간 「사려는 사람 vs 팔려는 사람」의 힘겨루기로 정해져. 회사가 돈 잘 벌면 사려는 사람이 많아져 오르고, 나빠지면 반대로 내려가.' },
  { id:'diversification', title:'분산투자', icon:'🧺',
    body:'"계란을 한 바구니에 담지 말라"는 말이 있어. 여러 회사·여러 업종에 나눠서 투자하면 하나가 망해도 다른 게 벌어줘서 손실을 줄일 수 있어.' },
  { id:'fee', title:'수수료와 세금', icon:'💸',
    body:'주식을 사고팔 때 증권사 수수료(약 0.015%)와 세금(팔 때 0.18%)이 붙어. 짧게 자주 사고팔면 이 비용이 커져서 수익이 깎여.' },
  { id:'longterm', title:'장기 투자 vs 단타', icon:'⏳',
    body:'좋은 회사를 오래 갖고 있으면 회사가 성장하는 만큼 주가도 커져. 짧게 사고파는 「단타」는 재밌지만 대부분 손실을 봐. 워런 버핏도 장기투자로 부자가 됨.' },
  { id:'value', title:'PER과 시가총액', icon:'🔍',
    body:'시가총액 = 주가 × 총 주식 수 = 회사의 값어치. PER = 시가총액 ÷ 순이익 = 「지금 이 값에 사면 이익으로 회수하는 데 몇 년 걸리나」. PER이 낮으면 싸다고 볼 수 있어.' },
  { id:'risk', title:'위험(변동성)', icon:'⚡',
    body:'주가가 크게 오르내리는 걸 「변동성이 높다」고 해. 게임·바이오는 변동성이 크고, 통신·금융은 작아. 큰 수익을 노리면 큰 손실도 각오해야 해.' },
  { id:'compound', title:'복리의 마법', icon:'🌱',
    body:'수익이 원금에 붙고, 그 다음 해엔 늘어난 원금에 다시 수익이 붙어. 연 10%씩 20년이면 원금의 6.7배가 돼. 아인슈타인이 "복리는 세계 8대 불가사의"라고 했대.' }
];

// 학습 미션 (게이미피케이션)
window.SSAMJI_MISSIONS = [
  { id:'m1', title:'첫 매수', desc:'아무 종목이나 1주 이상 매수해보기', reward:'🥉 초보 투자자', check:s=>s.trades.filter(t=>t.type==='buy').length>=1 },
  { id:'m2', title:'분산투자 실천', desc:'서로 다른 3개 업종에 투자하기', reward:'🥈 균형 투자자', check:s=>{ const cats=new Set(); Object.keys(s.holdings||{}).forEach(t=>{ const st=SSAMJI_STOCKS.find(x=>x.ticker===t); if(st&&s.holdings[t].qty>0) cats.add(st.category); }); return cats.size>=3; } },
  { id:'m3', title:'첫 이익 실현', desc:'매도로 이익 실현하기', reward:'💰 수익 실현', check:s=>s.trades.some(t=>t.type==='sell'&&(t.realizedPnl||0)>0) },
  { id:'m4', title:'거래 10회', desc:'매수·매도 합쳐 10회 이상 거래하기', reward:'📊 거래 숙련자', check:s=>s.trades.length>=10 },
  { id:'m5', title:'수익률 +10%', desc:'총 자산 수익률이 +10%를 넘기기', reward:'🚀 두 자릿수 수익', check:s=>((s.totalValue-s.seedMoney)/s.seedMoney)>=0.10 },
  { id:'m6', title:'1년 버티기', desc:'시뮬레이션 시간 365일 이상 진행하기', reward:'⏳ 장기 투자자', check:s=>s.daysPassed>=365 },
  { id:'m7', title:'거래일지 5회', desc:'매매 시 근거를 5회 이상 기록하기', reward:'📝 기록의 힘', check:s=>s.trades.filter(t=>t.reason&&t.reason.length>=10).length>=5 }
];
