// 국내 대기업 30종목 메타데이터 (학생 친숙 종목)
// 기술가정 연계: products 필드로 "이 회사가 만드는 물건" 노출
window.SSAMJI_STOCKS = [
  { ticker:'005930', name:'삼성전자', sector:'반도체·전자', logo:'📱',
    products:['갤럭시 스마트폰','메모리 반도체','TV·냉장고'],
    description:'세계 최대 메모리 반도체 제조사이자 갤럭시 스마트폰을 만드는 회사. 대한민국 시가총액 1위.',
    initialPrice:81000, drift:0.06, vol:0.28, category:'tech' },
  { ticker:'000660', name:'SK하이닉스', sector:'반도체', logo:'💾',
    products:['D램','낸드플래시','HBM(AI 반도체 메모리)'],
    description:'세계 2위 메모리 반도체 회사. AI 시대 필수품인 HBM을 삼성보다 먼저 성공.',
    initialPrice:118000, drift:0.10, vol:0.35, category:'tech' },
  { ticker:'373220', name:'LG에너지솔루션', sector:'2차전지', logo:'🔋',
    products:['전기차 배터리','ESS 배터리','노트북 배터리'],
    description:'테슬라·현대차·GM에 배터리를 공급하는 세계 2위 전기차 배터리 회사.',
    initialPrice:500000, drift:0.02, vol:0.35, category:'battery' },
  { ticker:'207940', name:'삼성바이오로직스', sector:'제약·바이오', logo:'💊',
    products:['바이오의약품 위탁생산(CMO)','신약 개발'],
    description:'세계 최대 바이오의약품 위탁생산 회사. 화이자·모더나 등의 백신·의약품을 대신 만들어 줌.',
    initialPrice:830000, drift:0.08, vol:0.30, category:'bio' },
  { ticker:'005380', name:'현대차', sector:'자동차', logo:'🚗',
    products:['그랜저','아이오닉','제네시스','수소전기차'],
    description:'세계 3위 자동차 그룹. 전기차 아이오닉과 프리미엄 브랜드 제네시스로 유명.',
    initialPrice:210000, drift:0.05, vol:0.25, category:'auto' },
  { ticker:'000270', name:'기아', sector:'자동차', logo:'🚙',
    products:['쏘렌토','스포티지','K5','EV6'],
    description:'현대차 그룹의 두 번째 완성차 회사. SUV와 전기차 EV6로 해외에서도 인기.',
    initialPrice:60000, drift:0.09, vol:0.28, category:'auto' },
  { ticker:'035420', name:'NAVER', sector:'IT·인터넷', logo:'🟢',
    products:['네이버 검색','네이버 웹툰','네이버페이','라인'],
    description:'한국 최대 포털·검색 회사. 웹툰·페이·클라우드까지 사업 확장.',
    initialPrice:293000, drift:-0.02, vol:0.32, category:'tech' },
  { ticker:'035720', name:'카카오', sector:'IT·인터넷', logo:'💛',
    products:['카카오톡','카카오페이','카카오뱅크','카카오T'],
    description:'카카오톡을 중심으로 은행·택시·페이까지 확장한 대표 IT 회사.',
    initialPrice:78000, drift:-0.08, vol:0.38, category:'tech' },
  { ticker:'066570', name:'LG전자', sector:'전자·가전', logo:'📺',
    products:['OLED TV','냉장고·세탁기','시그니처 가전'],
    description:'세계 1위 OLED TV 제조사. 프리미엄 가전 브랜드 시그니처로 유명.',
    initialPrice:150000, drift:0.02, vol:0.24, category:'tech' },
  { ticker:'006400', name:'삼성SDI', sector:'2차전지', logo:'🔌',
    products:['전기차 배터리','ESS','전자재료'],
    description:'BMW·아우디 등 유럽 프리미엄 전기차에 배터리를 공급하는 회사.',
    initialPrice:640000, drift:0.03, vol:0.32, category:'battery' },
  { ticker:'051910', name:'LG화학', sector:'화학·소재', logo:'🧪',
    products:['석유화학','배터리 소재','LG생명과학'],
    description:'국내 최대 화학 회사. 자회사 LG에너지솔루션 상장 후 화학·소재에 집중.',
    initialPrice:820000, drift:-0.02, vol:0.28, category:'chem' },
  { ticker:'005490', name:'POSCO홀딩스', sector:'철강·소재', logo:'⚙️',
    products:['철강(자동차·조선용)','리튬','2차전지 소재'],
    description:'세계 6위 철강회사. 최근 리튬·양극재 등 배터리 소재 사업 확장 중.',
    initialPrice:290000, drift:0.04, vol:0.30, category:'steel' },
  { ticker:'105560', name:'KB금융', sector:'금융', logo:'🏦',
    products:['국민은행','KB증권','KB카드','KB손해보험'],
    description:'국내 최대 종합금융그룹. 국민은행이 주력.',
    initialPrice:45000, drift:0.07, vol:0.22, category:'finance' },
  { ticker:'055550', name:'신한지주', sector:'금융', logo:'🏛️',
    products:['신한은행','신한카드','신한투자증권'],
    description:'국내 2위 금융지주. 배당을 많이 주는 대표적인 배당주.',
    initialPrice:38000, drift:0.06, vol:0.20, category:'finance' },
  { ticker:'068270', name:'셀트리온', sector:'제약·바이오', logo:'💉',
    products:['바이오시밀러(램시마 등)','자체 신약 개발'],
    description:'유럽·미국에 바이오시밀러(복제 바이오의약품)를 파는 대표 바이오 회사.',
    initialPrice:230000, drift:-0.03, vol:0.34, category:'bio' },
  { ticker:'259960', name:'크래프톤', sector:'게임', logo:'🎮',
    products:['배틀그라운드','펍지 모바일','인디게임'],
    description:'배틀그라운드로 세계적 인기를 얻은 게임 회사. 인도 시장에서 특히 강함.',
    initialPrice:490000, drift:-0.04, vol:0.40, category:'game' },
  { ticker:'352820', name:'하이브', sector:'엔터테인먼트', logo:'🎤',
    products:['BTS','뉴진스','세븐틴','위버스 팬 플랫폼'],
    description:'BTS 소속사에서 시작해 뉴진스·세븐틴까지 거느린 세계 최대 K-POP 회사.',
    initialPrice:290000, drift:0.02, vol:0.38, category:'ent' },
  { ticker:'035900', name:'JYP Ent.', sector:'엔터테인먼트', logo:'🎵',
    products:['트와이스','스트레이키즈','ITZY','엔믹스'],
    description:'박진영이 세운 3대 엔터 중 하나. 일본·미국에서도 성공적으로 확장.',
    initialPrice:47000, drift:0.03, vol:0.36, category:'ent' },
  { ticker:'036570', name:'엔씨소프트', sector:'게임', logo:'⚔️',
    products:['리니지M','리니지W','TL(쓰론앤리버티)'],
    description:'리니지로 유명한 국내 대표 MMORPG 회사. 최근 신작 부진으로 어려움.',
    initialPrice:930000, drift:-0.15, vol:0.42, category:'game' },
  { ticker:'293490', name:'카카오게임즈', sector:'게임', logo:'🎯',
    products:['오딘','우마무스메','아키에이지 워'],
    description:'카카오 계열 게임 퍼블리셔. 오딘으로 큰 성공을 거둔 뒤 후속작 준비 중.',
    initialPrice:55000, drift:-0.10, vol:0.42, category:'game' },
  { ticker:'097950', name:'CJ제일제당', sector:'식품', logo:'🍚',
    products:['비비고 만두·김치','햇반','다시다','슈완스(미국)'],
    description:'세계 만두 시장 1위. 비비고 브랜드로 K-푸드 세계화를 이끔.',
    initialPrice:400000, drift:0.03, vol:0.22, category:'food' },
  { ticker:'271560', name:'오리온', sector:'식품', logo:'🍫',
    products:['초코파이','포카칩','오!감자','중국·베트남 판매'],
    description:'초코파이의 그 회사. 중국·베트남·러시아에서도 매출이 큰 글로벌 제과회사.',
    initialPrice:140000, drift:0.02, vol:0.22, category:'food' },
  { ticker:'004370', name:'농심', sector:'식품', logo:'🍜',
    products:['신라면','짜파게티','새우깡','너구리'],
    description:'신라면·짜파게티의 그 회사. 영화 "기생충" 이후 짜파구리로 미국 매출 급증.',
    initialPrice:260000, drift:0.06, vol:0.24, category:'food' },
  { ticker:'005300', name:'롯데칠성', sector:'식품·음료', logo:'🥤',
    products:['칠성사이다','펩시','처음처럼','새로'],
    description:'국내 최대 음료·주류 회사. 사이다·소주·맥주까지 다 취급.',
    initialPrice:150000, drift:0.02, vol:0.20, category:'food' },
  { ticker:'090430', name:'아모레퍼시픽', sector:'화장품', logo:'💄',
    products:['설화수','라네즈','이니스프리','헤라'],
    description:'K-뷰티 대표 화장품 회사. 설화수·라네즈로 중국·미국에서 인기.',
    initialPrice:245000, drift:-0.06, vol:0.30, category:'cosmetic' },
  { ticker:'051900', name:'LG생활건강', sector:'생활용품·화장품', logo:'🧴',
    products:['후(궁중화장품)','엘라스틴','페리오','코카콜라 국내판'],
    description:'후·숨 등 럭셔리 화장품과 생활용품·음료를 함께 하는 종합 소비재 회사.',
    initialPrice:1500000, drift:-0.10, vol:0.28, category:'cosmetic' },
  { ticker:'139480', name:'이마트', sector:'유통', logo:'🛒',
    products:['이마트 매장','트레이더스','스타벅스코리아','SSG닷컴'],
    description:'국내 최대 대형마트. 스타벅스 코리아·SSG닷컴도 자회사.',
    initialPrice:170000, drift:-0.05, vol:0.24, category:'retail' },
  { ticker:'004170', name:'신세계', sector:'유통', logo:'🏬',
    products:['신세계백화점','면세점','조선호텔'],
    description:'국내 대표 백화점·면세점 회사. 이마트와 같은 신세계 그룹.',
    initialPrice:260000, drift:0.02, vol:0.26, category:'retail' },
  { ticker:'003490', name:'대한항공', sector:'항공·운송', logo:'✈️',
    products:['국제선 여객·화물','아시아나 합병 진행'],
    description:'국내 1위 항공사. 코로나 이후 화물로 큰돈 벌었고 아시아나와 합병 중.',
    initialPrice:26000, drift:0.05, vol:0.26, category:'transport' },
  { ticker:'017670', name:'SK텔레콤', sector:'통신', logo:'📡',
    products:['5G 이동통신','T우주 구독','SK브로드밴드'],
    description:'국내 1위 이동통신사. 배당을 많이 주는 대표 배당주 중 하나.',
    initialPrice:47000, drift:0.03, vol:0.16, category:'telecom' }
];

// 카테고리별 라벨 (필터 칩용)
window.SSAMJI_CATEGORIES = {
  tech:'💻 IT·전자', battery:'🔋 배터리', bio:'💊 바이오', auto:'🚗 자동차',
  chem:'🧪 화학·소재', steel:'⚙️ 철강', finance:'🏦 금융', game:'🎮 게임',
  ent:'🎤 엔터', food:'🍚 식품', cosmetic:'💄 화장품', retail:'🛒 유통',
  transport:'✈️ 항공·운송', telecom:'📡 통신'
};

// 경제 개념 미니 카드 (학습 탭) — keywords는 검색용
window.SSAMJI_CONCEPTS = [
  // ── 기초 ──
  { id:'stock', title:'주식이 뭐야?', icon:'📈', cat:'기초', keywords:'주식 주주 지분 소유권 회사조각',
    body:'회사가 사업 자금이 필요할 때 「이 회사의 조각」을 파는 게 주식. 주식을 사면 그 회사의 아주 작은 주인(주주)이 됨. 회사가 잘 되면 주식 값이 오르고 배당(이익 나눔)도 받을 수 있어.' },
  { id:'price', title:'왜 주가는 매일 오르내려?', icon:'📊', cat:'기초', keywords:'주가 시세 수요 공급 매수 매도 등락',
    body:'주가는 그 순간 「사려는 사람 vs 팔려는 사람」의 힘겨루기로 정해져. 회사가 돈 잘 벌면 사려는 사람이 많아져 오르고, 나빠지면 반대로 내려가.' },
  { id:'market_kospi', title:'코스피 vs 코스닥', icon:'🏛️', cat:'기초', keywords:'코스피 코스닥 지수 시장 대형주 중소형주',
    body:'코스피는 삼성전자처럼 크고 안정적인 대기업이 모인 시장, 코스닥은 상대적으로 작지만 성장성 높은 기술·벤처 기업이 많은 시장. 코스닥이 보통 더 많이 출렁여.' },
  { id:'index', title:'지수(코스피 지수)란?', icon:'🧮', cat:'기초', keywords:'지수 코스피지수 시장평균 포인트',
    body:'시장 전체 주가를 하나의 숫자로 나타낸 게 지수야. 코스피 지수가 오르면 «오늘은 대체로 주가가 올랐구나»를 한눈에 알 수 있어. 개별 종목이 아니라 시장 전체 분위기를 봐.' },
  { id:'candle', title:'시가·종가·고가·저가', icon:'🕯️', cat:'기초', keywords:'시가 종가 고가 저가 봉 캔들 차트',
    body:'하루 중 처음 값이 시가, 마지막 값이 종가, 가장 높았던 값이 고가, 가장 낮았던 값이 저가야. 이 네 값으로 그린 게 「봉(캔들) 차트」. 쌈지 거래는 그날 종가로 이뤄져.' },
  { id:'volume', title:'거래량이 뭐야?', icon:'📶', cat:'기초', keywords:'거래량 거래대금 매매 관심',
    body:'그날 사고판 주식의 수가 거래량이야. 거래량이 갑자기 늘면 «사람들의 관심이 몰렸다»는 신호. 좋은 뉴스든 나쁜 뉴스든 큰일이 생기면 거래량이 커져.' },

  // ── 투자 원칙 ──
  { id:'diversification', title:'분산투자', icon:'🧺', cat:'투자원칙', keywords:'분산 분산투자 계란 바구니 위험분산 포트폴리오',
    body:'"계란을 한 바구니에 담지 말라"는 말이 있어. 여러 회사·여러 업종에 나눠서 투자하면 하나가 망해도 다른 게 벌어줘서 손실을 줄일 수 있어.' },
  { id:'longterm', title:'장기 투자 vs 단타', icon:'⏳', cat:'투자원칙', keywords:'장기투자 단타 단기매매 버핏 인내',
    body:'좋은 회사를 오래 갖고 있으면 회사가 성장하는 만큼 주가도 커져. 짧게 사고파는 「단타」는 재밌지만 대부분 손실을 봐. 워런 버핏도 장기투자로 부자가 됨.' },
  { id:'dca', title:'분할매수(적립식)', icon:'🧊', cat:'투자원칙', keywords:'분할매수 적립식 코스트에버리징 나눠사기 평단',
    body:'한 번에 다 사지 않고 여러 번 나눠서 사는 방법. 값이 오르든 내리든 조금씩 사면 평균 사는 값이 안정돼서, 고점에 몰빵하는 실수를 줄일 수 있어.' },
  { id:'stoploss', title:'손절과 익절', icon:'✂️', cat:'투자원칙', keywords:'손절 익절 손절매 손실관리 규칙',
    body:'«-10%가 되면 판다»처럼 손실을 끊는 게 손절, 목표만큼 오르면 이익을 확정하는 게 익절. 규칙을 미리 정해두면 감정에 휘둘리지 않고 큰 손실을 막을 수 있어.' },
  { id:'rebalancing', title:'리밸런싱', icon:'⚖️', cat:'투자원칙', keywords:'리밸런싱 비중조절 재조정 균형',
    body:'시간이 지나면 한 종목만 많이 올라서 비중이 커져. 가끔 «오른 건 조금 팔고, 덜 오른 건 채워서» 원래 계획한 비율로 되돌리는 게 리밸런싱이야.' },

  // ── 위험과 심리 ──
  { id:'risk', title:'위험(변동성)', icon:'⚡', cat:'위험·심리', keywords:'위험 변동성 리스크 등락폭',
    body:'주가가 크게 오르내리는 걸 「변동성이 높다」고 해. 게임·바이오는 변동성이 크고, 통신·금융은 작아. 큰 수익을 노리면 큰 손실도 각오해야 해.' },
  { id:'risk_return', title:'수익과 위험은 짝꿍', icon:'🎢', cat:'위험·심리', keywords:'수익 위험 리스크 하이리스크 관계 트레이드오프',
    body:'«위험이 낮은데 수익만 높은» 투자는 거의 없어. 크게 벌 수 있는 건 크게 잃을 수도 있다는 뜻. 그래서 내가 견딜 수 있는 위험만큼만 투자하는 게 중요해.' },
  { id:'fomo', title:'포모(FOMO)와 추격매수', icon:'🏃', cat:'위험·심리', keywords:'포모 fomo 추격매수 조급함 뇌동매매 유행',
    body:'«나만 못 벌면 어쩌지?» 하는 조급함이 FOMO야. 뉴스 보고 급하게 따라 사면 이미 오른 고점일 때가 많아. 한 박자 쉬고 «왜 사는지» 설명할 수 있을 때 사자.' },
  { id:'emotion', title:'공포와 탐욕', icon:'😱', cat:'위험·심리', keywords:'공포 탐욕 심리 감정 패닉 군중심리',
    body:'가장 흔한 실수는 «공포에 팔고 탐욕에 사는» 거야. 다 떨어질 때 무서워서 팔고, 다 오를 때 욕심나서 사면 손해 보기 쉬워. 미리 세운 원칙대로 움직이자.' },
  { id:'bubble', title:'거품(버블)', icon:'🫧', cat:'위험·심리', keywords:'거품 버블 과열 튤립 폭락',
    body:'실제 가치보다 값이 지나치게 부풀어 오른 상태가 거품이야. 모두가 «계속 오른다»고 믿을 때 위험해. 거품이 터지면 순식간에 크게 빠지니 과열 신호를 조심해.' },

  // ── 가치 평가 ──
  { id:'value', title:'PER과 시가총액', icon:'🔍', cat:'가치평가', keywords:'per 시가총액 밸류 저평가 고평가 배수',
    body:'시가총액 = 주가 × 총 주식 수 = 회사의 값어치. PER = 시가총액 ÷ 순이익 = 「지금 이 값에 사면 이익으로 회수하는 데 몇 년 걸리나」. PER이 낮으면 싸다고 볼 수 있어.' },
  { id:'financials', title:'매출과 영업이익', icon:'📑', cat:'가치평가', keywords:'매출 영업이익 실적 재무제표 이익 어닝',
    body:'매출은 회사가 번 돈 전체, 영업이익은 그중 비용을 빼고 실제로 남긴 돈이야. 실적이 좋아지면(«어닝 서프라이즈») 주가가 오르는 힘이 돼. 회사가 돈을 잘 버는지 보는 핵심 숫자.' },
  { id:'per_pbr', title:'싸다·비싸다는 어떻게 알아?', icon:'🏷️', cat:'가치평가', keywords:'per pbr 저평가 고평가 밸류에이션 업종비교',
    body:'주가가 싼지 비싼지는 값 자체가 아니라 «이익·자산에 비해»로 봐. 같은 업종끼리 PER을 비교하면 힌트가 돼. 단, 업종마다 기준이 달라서 게임주와 은행주를 그냥 비교하면 안 돼.' },

  // ── 수익·복리 ──
  { id:'compound', title:'복리의 마법', icon:'🌱', cat:'수익·복리', keywords:'복리 눈덩이 재투자 시간',
    body:'수익이 원금에 붙고, 그 다음 해엔 늘어난 원금에 다시 수익이 붙어. 연 10%씩 20년이면 원금의 6.7배가 돼. 아인슈타인이 "복리는 세계 8대 불가사의"라고 했대.' },
  { id:'rule72', title:'72의 법칙', icon:'🔢', cat:'수익·복리', keywords:'72법칙 두배 복리계산 수익률',
    body:'72 ÷ 수익률(%) = 원금이 두 배 되는 데 걸리는 대략의 연수. 연 6%면 72÷6=12년, 연 12%면 6년. 높은 수익률이 시간을 얼마나 줄이는지 빠르게 가늠할 수 있어.' },
  { id:'dividend', title:'배당금', icon:'💵', cat:'수익·복리', keywords:'배당 배당금 배당수익률 주주환원 현금',
    body:'회사가 번 이익의 일부를 주주에게 나눠주는 돈이 배당금. 주가가 안 올라도 배당을 주는 회사를 갖고 있으면 은행 이자처럼 현금을 받을 수 있어.' },

  // ── 비용 ──
  { id:'fee', title:'수수료와 세금', icon:'💸', cat:'비용', keywords:'수수료 세금 거래세 비용 매매비용',
    body:'주식을 사고팔 때 증권사 수수료(약 0.015%)와 세금(팔 때 0.18%)이 붙어. 짧게 자주 사고팔면 이 비용이 커져서 수익이 깎여.' },

  // ── 상품·종류 ──
  { id:'etf', title:'ETF가 뭐야?', icon:'🧺', cat:'상품', keywords:'etf 인덱스 상장지수펀드 분산 바구니',
    body:'여러 종목을 한 바구니에 담아 통째로 사고파는 상품이 ETF. 하나만 사도 자동으로 분산투자가 돼서 초보의 위험을 크게 줄여줘. 예: 「코스피200 ETF」를 사면 대형주 200개에 한 번에 투자.' },
  { id:'index_fund', title:'인덱스(패시브) 투자', icon:'📇', cat:'상품', keywords:'인덱스 패시브 지수추종 시장평균',
    body:'«시장 전체를 그대로 따라 사는» 방법. 어떤 종목이 오를지 맞히려 애쓰지 않고 지수를 통째로 담아 시장 평균 수익을 노려. 길게 보면 대부분의 전문가보다 성적이 좋은 경우도 많아.' },
  { id:'bond', title:'주식 vs 채권', icon:'🏦', cat:'상품', keywords:'채권 국채 이자 안전 주식비교',
    body:'채권은 나라·회사에 «돈을 빌려주고 이자를 받는» 것. 주식보다 안전하지만 크게 벌긴 어려워. 주식(위험·고수익)과 채권(안전·저수익)을 섞으면 충격을 줄일 수 있어.' },
  { id:'bluechip', title:'우량주·성장주·테마주', icon:'🏅', cat:'상품', keywords:'우량주 성장주 테마주 대형주 블루칩',
    body:'우량주는 크고 안정적인 회사, 성장주는 빠르게 크는 회사, 테마주는 특정 이슈로 잠깐 뜨는 종목. 테마주는 오르내림이 극심해서 초보에겐 위험해.' },

  // ── 시장 흐름 ──
  { id:'bull_bear', title:'강세장 vs 약세장', icon:'🐂', cat:'시장흐름', keywords:'강세장 약세장 불장 베어마켓 상승장 하락장',
    body:'주가가 전반적으로 오르는 시기를 강세장(불마켓 🐂), 내리는 시기를 약세장(베어마켓 🐻)이라 해. 지금이 어떤 국면인지 알면 마음가짐을 정하는 데 도움이 돼.' },
  { id:'cycle', title:'경기 호황과 불황', icon:'🔄', cat:'시장흐름', keywords:'경기 호황 불황 사이클 경기순환',
    body:'경제는 좋아졌다 나빠졌다를 반복해(경기 순환). 호황엔 소비·투자가 늘어 주가가 오르기 쉽고, 불황엔 반대야. 주가는 실제 경기보다 조금 먼저 움직이는 편.' },
  { id:'semiconductor', title:'반도체 사이클', icon:'💽', cat:'시장흐름', keywords:'반도체 사이클 삼성전자 하이닉스 메모리 호황불황',
    body:'반도체는 호황과 불황이 주기적으로 반복돼. 값이 오르면 너도나도 만들어 공급이 넘치고, 다시 값이 떨어지는 식. 삼성전자·SK하이닉스 주가는 이 사이클을 크게 타.' },

  // ── 거시경제 ──
  { id:'interest', title:'금리와 주가', icon:'🏛️', cat:'거시경제', keywords:'금리 이자율 연준 기준금리 인상 성장주',
    body:'금리가 오르면 안전한 예금 이자가 좋아지고, 빚내서 투자하기도 부담돼서 주가엔 대체로 나빠. 특히 미래 이익이 큰 성장주(기술·게임)가 금리 인상에 약해.' },
  { id:'inflation', title:'인플레이션(물가)', icon:'🎈', cat:'거시경제', keywords:'인플레이션 물가 cpi 화폐가치 금리',
    body:'물건 값이 전반적으로 오르는 게 인플레이션. 물가가 너무 빨리 오르면 중앙은행이 «금리를 올려서» 잡으려 해. 그래서 물가 뉴스가 주가에도 큰 영향을 줘.' },
  { id:'fx', title:'환율과 주가', icon:'💱', cat:'거시경제', keywords:'환율 원달러 달러 강달러 수출 외국인',
    body:'원/달러 환율이 오르면(원화 약세) 외국인 투자자가 빠져나가기 쉬워 증시에 부담이 돼. 반대로 수출로 달러를 버는 기업(자동차·반도체)엔 도움이 되기도 해.' },
  { id:'safehaven', title:'안전자산(금·달러)', icon:'🪙', cat:'거시경제', keywords:'안전자산 금 달러 국채 위기 헤지',
    body:'전쟁·경제 위기처럼 무서운 일이 생기면 사람들은 금·달러·국채 같은 «안전자산»으로 몰려. 위험한 주식에서 돈이 빠져 안전한 곳으로 옮겨가는 흐름을 이해하면 좋아.' },

  // ── 거래·제도 ──
  { id:'order', title:'시장가 vs 지정가', icon:'🧾', cat:'거래·제도', keywords:'시장가 지정가 주문 체결 호가',
    body:'시장가는 «지금 값에 바로» 사고파는 주문, 지정가는 «이 값이 되면» 사고파는 예약 주문이야. 쌈지는 그날 종가로 바로 체결되는 시장가 방식으로 단순하게 만들었어.' },
  { id:'ipo', title:'공모주(IPO)·상장', icon:'🎉', cat:'거래·제도', keywords:'ipo 공모주 상장 신규상장 청약',
    body:'회사가 처음으로 주식 시장에 데뷔하는 게 상장(IPO). 상장 전에 미리 주식을 살 기회를 «공모주 청약»이라 해. 인기 있는 공모주는 첫날 크게 오르기도, 반대로 빠지기도 해.' },
  { id:'shortselling', title:'공매도', icon:'🔻', cat:'거래·제도', keywords:'공매도 하락 빌려서팔기 숏',
    body:'주식을 «빌려서 먼저 팔고» 나중에 값이 내리면 싸게 사서 갚아 차익을 남기는 방법. 주가 하락에 베팅하는 거라 초보에겐 매우 위험하고, 규제도 많아.' }
];

// 학습 미션 (게이미피케이션)
window.SSAMJI_MISSIONS = [
  { id:'m1', title:'첫 매수', desc:'아무 종목이나 1주 이상 매수해보기', reward:'🥉 초보 투자자', check:s=>s.trades.filter(t=>t.type==='buy').length>=1 },
  { id:'m2', title:'분산투자 실천', desc:'서로 다른 3개 업종에 투자하기', reward:'🥈 균형 투자자', check:s=>{ const cats=new Set(); Object.keys(s.holdings||{}).forEach(t=>{ const st=SSAMJI_STOCKS.find(x=>x.ticker===t); if(st&&s.holdings[t].qty>0) cats.add(st.category); }); return cats.size>=3; } },
  { id:'m3', title:'첫 이익 실현', desc:'매도로 이익 실현하기', reward:'💰 수익 실현', check:s=>s.trades.some(t=>t.type==='sell'&&(t.realizedPnl||0)>0) },
  { id:'m4', title:'거래 10회', desc:'매수·매도 합쳐 10회 이상 거래하기', reward:'📊 거래 숙련자', check:s=>s.trades.length>=10 },
  { id:'m5', title:'수익률 +10%', desc:'총 자산 수익률이 +10%를 넘기기', reward:'🚀 두 자릿수 수익', check:s=>((s.totalValue-s.seedMoney)/s.seedMoney)>=0.10 },
  { id:'m6', title:'1년 버티기', desc:'시뮬레이션 시간 365일 이상 진행하기', reward:'⏳ 장기 투자자', check:s=>s.daysPassed>=365 },
  { id:'m7', title:'거래일지 5회', desc:'매매 시 근거를 5회 이상 기록하기', reward:'📝 기록의 힘', check:s=>s.trades.filter(t=>t.reason&&t.reason.length>=10).length>=5 },
  { id:'m8', title:'몰빵은 금물', desc:'종목을 사되 현금을 20% 이상 남겨두기', reward:'💵 현금 지킴이', check:s=>s.trades.some(t=>t.type==='buy') && s.totalValue>0 && (s.cash/s.totalValue)>=0.20 },
  { id:'m9', title:'관심 종목 부자', desc:'서로 다른 5개 종목을 동시에 보유하기', reward:'🧺 분산 마스터', check:s=>{ let n=0; Object.keys(s.holdings||{}).forEach(t=>{ if(s.holdings[t].qty>0) n++; }); return n>=5; } },
  { id:'m10', title:'뉴스 탐정', desc:'오늘의 뉴스에서 이슈 기록지 3건 이상 쓰기', reward:'🔎 뉴스 탐정', check:s=>{ try{ return window.SSAMJI_NEWS && SSAMJI_NEWS.getNotes().length>=3; }catch(e){ return false; } } }
];
